---
name: CI.Ansibel-Inventory-Render

on:
  push:
    branches: [ "dev/**", "devops" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint ansible-inventory .
      - name: Lint with pylint
        run: |
          pylint --recursive=y -d C,W ./src
      - name: Verify with example data and ansible-inventory
        run: |
          python src/ansible-inventory-render/render.py -v examples/vars.yml -t examples/inventory.j2
          ansible-inventory -i inventory.yml --graph | tee inventory-graph
          ((exit 1) || [[ -z $(grep "Failed to parse" inventory-graph) ]] && exit 0)

      - name: Run Snyk to check for vulnerabilities
        run: |
          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
          snyk code test --org=rz
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
