name: CI.Ansibel-Inventory-Render

on:
  push:
    branches: [ "devops" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ansible-inventory 
        if [ -f reqs.txt ]; then pip install -r reqs.txt; fi
    - name: Lint with pylint
      run: |
        pylint --recursive=y -d C,W .
    - name: Verify with example data and ansible-inventory
      run: |
        python render.py -v example/vars.yml -t example/inventory.j2
        ansible-inventory -i inventory.yml --graph | tee inventory-graph
        ((exit 1) || [[ -z $(grep "Failed to parse" inventory-graph) ]] && exit 0)

